name: One App Development Image Build
on:
  repository_dispatch:
    types: [one-app-docker-dev-build]
jobs:
  one-app-docker-dev-build:
    name: Build Production Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build development docker image
        run: docker build -t dev . --target=development
      - name: Trigger Image Publishing
        uses: octokit/request-action@v2.x
        id: dispatch_one_app_tag_images
        with:
          route: POST /repos/:repository/dispatches
          repository: ${{ github.repository }}
          mediaType: '{"previews": ["everest"]}'
          event_type: "one-app-tag-images"
          client_payload: '{"docker_tag_version": "${{ github.event.client_payload.docker_tag_version }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
