name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid 
    # using to prevent processing unnecessary events.
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      # Basic configuration
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.PA_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: prepare-release
          permission: none
          issue-type: pull-request
