name: one-app-release
on:
  push:
    branches:
      - master
jobs:
  one-app-release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: new one-app release
        id: vars
        run: |
          NODE_ENV=development npm ci
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm run release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: One App Release Changes
          committer: Nelly Kiboi <nellyk@users.noreply.github.com>
          title: release changes
          body: This is an auto-generated PR with One App release changes
          labels: release, automated pr,skip-release-drafter
          reviewers: nellyk
          branch: release-automated
          base: master
